#!/bin/sh /etc/rc.common

USE_PROCD=1
START=70
STOP=10

start_service() {
    procd_open_instance
    procd_set_param command /sbin/insmod /lib/modules/$(uname -r)/pcie_mhi.ko
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    /sbin/rmmod pcie_mhi
}

service_triggers() {
    procd_add_reload_trigger pcie_mhi
}

restart() {
    stop
    sleep 2
    start
}
